name: "updateVisuals"
on:
  push:
    branches: [ "main" ]
    
jobs:
  update:
    name: Update
    runs-on: 'ubuntu-latest'
    permissions:
      actions: write
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Repo Visualizer
      uses: githubocto/repo-visualizer@0.9.1
      with:
        output_file: "/project-files/diagram.svg"
        excluded_paths: "dist,node_modules"
