name: "updateVisuals"
on:
  push:
    branches: [ "main" ]
    
jobs:
  update:
    name: Update
    runs-on: 'ubuntu-latest'
    permissions:
      actions: write
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Import code-signing key
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.ACTIONS_PULL_KEY }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true
    - name: Repo Visualizer
      uses: githubocto/repo-visualizer@0.9.1
      with:
        output_file: "./project-files/diagram.svg"
        excluded_paths: "dist,node_modules"
